name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a multi-line script
      env:
        MASKINBRUKER_PGP_KEY: ${{ secrets.MASKINBRUKER_PGP_KEY }}
      run: |
        echo $MASKINBRUKER_PGP_KEY
        echo $MASKINBRUKER_PGP_KEY | gpg --import
        gpg --decrypt ikke_temmelig_hemmelig.yaml.secret
        cat ikke_temmelig_hemmelig.yaml

